services:
  arduino-cli:
    extends:
      file: compose.yaml
      service: arduino-cli
    devices:
      # Map all potential USB devices
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
    # Add group to access USB devices
    group_add:
      - dialout