services:
  core-builder:
    build:
      context: ./docker/core-builder
      dockerfile: Dockerfile
    volumes:
      - ./dist:/chipkit/dist
      - ./tmp:/chipkit/tmp
    environment:
      - ANT_CACHE=/chipkit/tmp

  arduino-cli:
    build:
      context: ./docker/arduino-cli
    volumes:
      - ./:/workspace
      - ./arduino_data:/home/arduino/arduino_data
      - ./dist/linux32/chipkit-core/pic32:/home/arduino/arduino_data/packages/chipKIT/hardware/pic32/2.1.0
      # Mount just the bin directory with compiler tools
      - ./dist/linux32/chipkit-core/pic32/compiler/pic32-tools:/home/arduino/arduino_data/packages/chipKIT/tools/pic32-tools/1.43
      # Mount pic32prog
      - ./dist/linux32/chipkit-core/pic32/tools/bin/pic32prog:/home/arduino/arduino_data/packages/chipKIT/tools/pic32prog/1.0.0/pic32prog
      - ./tmp:/workspace/tmp
    environment:
      - ARDUINO_DIRECTORIES_DATA=/home/arduino/arduino_data
      - ARDUINO_DIRECTORIES_DOWNLOADS=/home/arduino/arduino_data/staging
      - ARDUINO_DIRECTORIES_USER=/home/arduino/Arduino
    depends_on:
      - core-builder