services:
  arduino-cli:
    extends:
      file: compose.yaml
      service: arduino-cli
    devices:
      # Map only the ACM port since that's what we're using
      - /dev/ttyACM0:/dev/ttyACM0
    # Add group to access USB devices
    group_add:
      - dialout