board_manager:
  additional_urls:
    - https://github.com/chipKIT32/chipKIT-core/raw/master/package_chipkit_index.json

directories:
  data: /home/arduino/arduino_data
  downloads: /home/arduino/arduino_data/staging
  user: /home/arduino/Arduino

library:
  enable_unsafe_install: true